### PR TITLE
Added Few more algorithms

### PR DESCRIPTION
**Pull request by rg1107**
Added Sieve of Eratosthenes, bubble sort and Fibonacci.

### CODE REVIEW

**Comment by AshishOhri** [comment]
Thanks for contributing but please follow the <a href="https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md">Contributing Guidelines</a> and naming conventions in the guidelines accordingly. 😄

**Comment by rg1107** [comment]
Sure.

**Comment by rg1107** [comment]
solved issue #33 and followed guidelines.

**Comment by rg1107** [comment]
Thank you

**Pull request merged**
