### PR TITLE
Create python_hashable_dict.py

### PR DESCRIPTION
**Pull request by sashaaero**

### CODE REVIEW

**Comment by iam-Shashank** [comment]
Please explain your code. Where have you used the class which you created? There needs to be some input/output for us to check the code. Either hard-coded or user taken.

**Comment by sashaaero** [comment]
We use this structure in PonyORM. Since standard dict is not hashable, this one can be added in Set.
Okay, I will add some code later.

**Comment by sashaaero** [comment]
How do I provide come usage code? Place it into the file or create another one?

**Comment by iam-Shashank** [comment]
same file.  We just need some input, output code to check it's working and also, if anyone else refers to this code. Just like in all other algorithms people take in user input/output or hard-code some values manually. Hope that clears the confusion.

**Pull request merged**
