### PR TITLE
#94 Added Merge Sort for C 

### PR DESCRIPTION
**Pull request by Sarvesh18**
Added Merge Sort for C.
Issue No is #94

### CODE REVIEW

**Comment by subhahu123** [comment]
> Added Merge Sort for C.

please add issue no.

**Comment by Sarvesh18** [comment]
Issue No is #94

**Comment by subhahu123** [comment]
> Issue No is #94

add this in ur description

**Comment by Sarvesh18** [comment]
@subhahu123 
Updated

**Comment by subhahu123** [comment]
> @subhahu123
> Updated Pls Merge.

u have still added this into ur pr desciption
u r adding it into the comments
but i m doing it for u so that u know that what i mean to say
for now , i m merging the code 
from next time please follow the guidelines

**Pull request merged**
