### PR TITLE
c++-egg-dropping-puzzle-O(nk^2).cpp

### PR DESCRIPTION
**Pull request by yashasvi25**
This is a fix to the issue #108 .
Changes made :
* This adds an algorithm to solve the egg dropping puzzle using dynamic programming approach in C++.

### CODE REVIEW

**Comment by subhahu123** [comment]
> _No description provided._

please open the issue first for this like we have for others

**Comment by yashasvi25** [comment]
> > _No description provided._
> 
> please open the issue first for this like we have for others

Done

**Comment by subhahu123** [comment]
> > > _No description provided._
> > 
> > 
> > please open the issue first for this like we have for others
> 
> Done

add the issue in desciption of pull request also like   Fix #75

**Comment by yashasvi25** [comment]
Done

**Pull request merged**
