### PR TITLE
fixes #92: adds merge sort algorithm in JS

### LINKED ISSUE #92: Create Merge_Sort_Algo implementation in Javascript
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

### PR DESCRIPTION
**Pull request by stackyism**
This PR fixes issue #92 
@subhahu123 Please let me know if any further changes are required.
Thanks! :)

### CODE REVIEW

**Comment by subhahu123** [comment]
> @subhahu123 Please let me know if any further changes are required.
> Thanks! :)

add issue no.
like fixes: #45

**Comment by stackyism** [comment]
@subhahu123 added issue no. #92 in both commit message & pull request header.

**Comment by subhahu123** [comment]
> @subhahu123 added issue no. #92 in both commit message & pull request header.

add it to pull request description also

**Comment by stackyism** [comment]
> > @subhahu123 added issue no. #92 in both commit message & pull request header.
> 
> add it to pull request description also

updated.
Thank You!

**Comment by stackyism** [comment]
Hey @subhahu123 .
Any further actions required from my side?

Thanks.

**Pull request merged**
